### MBA FP-gorwth algorithm to geenerate new bundles from most purschased bundles togather

In [ ]:
import pandas as pd
import os

In [6]:
DATA_PATH: str = r"C:\Users\Alber\Desktop\uni\GraduationProject\datasets\daily subscriptions"
FILEs: str = [rf'{DATA_PATH}\daily_sub_202508_with_locations_mobiles.csv',
            rf'{DATA_PATH}\daily_sub_202509_with_locations_mobiles.csv',
            rf'{DATA_PATH}\daily_sub_202510_with_locations_mobiles.csv'
]
SAVE_TO: str = r"C:\Users\Alber\Desktop\uni\GraduationProject\datasets\weekly purchases"

In [23]:
data = pd.read_csv(FILEs[0], 
    usecols=['msisdn', 'tbl_dt', 'bundle_name', 'bundle_id', 'total_rev', 'subscriptions']
)
data = data[(data['total_rev'] > 0) & (data['subscriptions'] > 0)]
data.shape

(45985969, 6)

In [24]:
data.head(10)

,tbl_dt,msisdn,bundle_id,bundle_name,subscriptions,total_rev
0,20250809,242069835561,SMSPK50,SMS Bundle 2 Days @66F,1,66.0
1,20250809,242064381075,FVX1D200FV3,Forfait Maxivoice 16Mins 1 jour@200F,1,200.0
2,20250809,242067637060,FVX1D200FV3,Forfait Maxivoice 16Mins 1 jour@200F,2,400.0
3,20250809,242067907977,SMSPK50,SMS Bundle 2 Days @66F,1,66.0
4,20250809,242061299388,36772,Whatsapp txt 1 jour@100F,1,100.0
5,20250809,242065583899,36769,Forfait Maximise 3.5GB 1 jour + Free Tik tok@1...,1,1300.0
6,20250821,242064022474,37249,Inbound Data Acceleration 100MB 1 day@100F,1,100.0
7,20250821,242064115736,36000,Forfait DIY VOICE ONNET,1,135.0
8,20250821,242064421850,36000,Forfait DIY VOICE ONNET,1,180.0
9,20250821,242065963316,SMSPK25,SMS Bundle 1 Day @41F,1,41.0

In [25]:
data['tbl_dt'] = pd.to_datetime(data['tbl_dt'], format='%Y%m%d')
data['YEAR'] = data['tbl_dt'].dt.year.astype(int)

data['WEEKNUMBER'] = data['tbl_dt'].dt.isocalendar().week

In [26]:
weekly_purchases = (
    data
    .groupby(['msisdn', 'WEEKNUMBER', 'bundle_name', 'bundle_id'], as_index=False)
    .agg({
        'total_rev': 'sum',
        'subscriptions': 'sum',
        'YEAR': 'first'
    })
)
weekly_purchases.shape

(26000882, 7)

In [27]:
weekly_purchases['WEEKNUMBER'] = weekly_purchases['WEEKNUMBER'].astype(int)

In [28]:
weekly_purchases.head(10)

,msisdn,WEEKNUMBER,bundle_name,bundle_id,total_rev,subscriptions,YEAR
0,242061000000,33,Forfait maximise 1.5GB 1 jours@650F,35054,650.0,1,2025
1,242061000000,33,Forfait weekend 3.17GB 3jours@840F,36826,840.0,1,2025
2,242061000000,34,Forfait maximise 1.5GB 1 jours@650F,35054,650.0,1,2025
3,242061000000,34,MagicNet 825MB 7 Jours@1200F,36965,1200.0,1,2025
4,242061000000,35,MagicNet 484MB 7 Jours@750F,36964,750.0,1,2025
5,242061000303,32,MaGicvoice 40+3Mins 7 jours@525F,FVX7D525FV4,525.0,1,2025
6,242061000404,31,Forfait Weekend 1.05GB 1 jours + 5 Mins@500F,36825,500.0,1,2025
7,242061000404,31,Forfait weekend 780MB 1jours@350F,36824,350.0,1,2025
8,242061000404,31,Ndeko_19Mins 1 jour@230F,80066,230.0,1,2025
9,242061000404,31,SMS Bundle 2 Days @66F,SMSPK50,66.0,1,2025

In [29]:
file_path = os.path.join(SAVE_TO, "weekly-purchase-202508.csv")
weekly_purchases.to_csv(file_path, index=False)

### Apply MBA ( we assume that weekly_purchases is table in MinTel Database schema)

In [16]:
import pandas as pd
import pyspark
from pyspark.sql import SparkSession, Row
from pyspark.ml.fpm import FPGrowth
from pyspark.sql.functions import col, expr, split, regexp_replace, trim, lit, concat, count, collect_list, isnan, when

In [8]:
# init spark
APP_NAME: str = "WEEKLY_MBA"

spark = SparkSession\
    .builder\
    .appName(APP_NAME)\
    .config("spark.driver.extraJavaOptions", "-Djava.security.manager=allow")\
    .config("spark.executor.extraJavaOptions", "-Djava.security.manager=allow")\
    .master("local[*]")\
    .config("spark.driver.memory", "16g")\
    .getOrCreate()

spark

In [9]:
DATA_PATH_W: str = r"C:\Users\Alber\Desktop\uni\GraduationProject\datasets\weekly purchases"
FILES_W: str = [rf'{DATA_PATH_W}\weekly-purchase-202508.csv',
            rf'{DATA_PATH_W}\weekly-purchase-202509.csv',
            rf'{DATA_PATH_W}\weekly-purchase-202510.csv'
]

In [10]:
data = spark.read.csv(
    FILES_W,
    header=True,
    inferSchema=True
).select("msisdn", "WEEKNUMBER", "bundle_name")

In [11]:
print((data.count(), len(data.columns)))

(69521293, 3)

In [13]:
data = data.filter(
    ~col("bundle_name").rlike("(?i)free|bonus|DIY")
)
data.count()

57476755

In [14]:
data.show(10, 0)

+------------+----------+--------------------------------------------+
|msisdn      |WEEKNUMBER|bundle_name                                 |
+------------+----------+--------------------------------------------+
|242061000000|33        |Forfait maximise 1.5GB 1 jours@650F         |
|242061000000|33        |Forfait weekend 3.17GB 3jours@840F          |
|242061000000|34        |Forfait maximise 1.5GB 1 jours@650F         |
|242061000000|34        |MagicNet 825MB 7 Jours@1200F                |
|242061000000|35        |MagicNet 484MB 7 Jours@750F                 |
|242061000303|32        |MaGicvoice 40+3Mins 7 jours@525F            |
|242061000404|31        |Forfait Weekend 1.05GB 1 jours + 5 Mins@500F|
|242061000404|31        |Forfait weekend 780MB 1jours@350F           |
|242061000404|31        |Ndeko_19Mins 1 jour@230F                    |
|242061000404|31        |SMS Bundle 2 Days @66F                      |
+------------+----------+--------------------------------------------+
only showing top 10 rows

In [17]:
# Aggregate transactions per user per week
data = data.withColumn("transaction_id", concat(col("msisdn"), lit("_"), col("WEEKNUMBER")))
# trs = data.groupBy("msisdn", "WEEKNUMBER", "MONTHNUMBER").agg(collect_list("bundle_name").alias("bundle_names"))
trs = data.groupBy("transaction_id").agg(collect_list("bundle_name").alias("bundle_list"))

In [28]:
trs.show(10, 0)

+---------------+------------------------------------------------------------------------------------------------------------------------------------------+
|transaction_id |bundle_list                                                                                                                               |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------+
|242061000000_35|[MagicNet 484MB 7 Jours@750F]                                                                                                             |
|242061000000_44|[MagicNet 825MB 7 Jours@1200F]                                                                                                            |
|242061000404_31|[Forfait Weekend 1.05GB 1 jours + 5 Mins@500F, Forfait weekend 780MB 1jours@350F, Ndeko_19Mins 1 jour@230F, SMS Bundle 2 Days @66F ]      |
|242061000505_35|[Forfait Maxivoice 16Mins 1 jour@200F]                                                                                                    |
|242061000505_40|[Forfait Maxivoice 16Mins 1 jour@200F]                                                                                                    |
|242061001010_37|[Illimite 2H@250F, Ndeko_11Mins 1 jour@185F]                                                                                              |
|242061001111_43|[SDP VAS]                                                                                                                                 |
|242061013547_38|[Ndeko_11Mins 1 jour@185F]                                                                                                                |
|242061013552_39|[SMS Bundle 1 Day @26F ]                                                                                                                  |
|242061013564_34|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, 50 SMS vers MTN ou 16 vers autre 2 jours@66F, MTN Call Me Back, Ndeko_11Mins 1 jour@185F]|
+---------------+------------------------------------------------------------------------------------------------------------------------------------------+
only showing top 10 rows

In [18]:
trs.count()

24014943

In [29]:
# Apply FP-Growth algorithm
min_support: float = 0.001 # Increase support to reduce rare itemsets
min_confidence: float = 0.5 # Increase confidence to keep only stronger rules
# Remove duplicates in the "bundle_name" array if exists.
trs = trs.withColumn("bundle_list", expr("array_distinct(bundle_list)"))
# run FP-Growth Algorithm
fp_growth = FPGrowth(itemsCol="bundle_list", 
                        minSupport=min_support,
                        minConfidence=min_confidence)
model = fp_growth.fit(trs)

In [24]:
model

FPGrowthModel: uid=FPGrowth_ba070799744e, numTrainingRecords=24014943

In [21]:
print("Frequent Itemsets Without Free Bundles:")
frq_itemssets = model.freqItemsets.show(n=100, truncate=False)
frq_itemssets
freq_rules_df = pd.DataFrame(model.freqItemsets.collect(), columns=model.freqItemsets.columns)
freq_rules_df.to_csv("no_free_bundles_freq_rules_weekly.csv", index=False)

Frequent Itemsets Without Free Bundles:
+---------------------------------------------------------------------------------------------------+-------+
|items                                                                                              |freq   |
+---------------------------------------------------------------------------------------------------+-------+
|[Forfait Maxivoice 16Mins 1 jour@200F]                                                             |4720129|
|[Forfait weekend 780MB 1jours@350F]                                                                |619515 |
|[Forfait Maxivoice 5Mins 1 jour@100F]                                                              |4213511|
|[Forfait Maxivoice 5Mins 1 jour@100F, Forfait Maxivoice 16Mins 1 jour@200F]                        |1158706|
|[MTN Call Me Back]                                                                                 |589922 |
|[SMS Bundle 1 Day @26F ]                                                                           |3937601|
|[SMS Bundle 1 Day @26F , Forfait Maxivoice 16Mins 1 jour@200F]                                     |849900 |
|[SMS Bundle 1 Day @26F , Forfait Maxivoice 5Mins 1 jour@100F]                                      |903038 |
|[SMS Bundle 1 Day @26F , Forfait Maxivoice 5Mins 1 jour@100F, Forfait Maxivoice 16Mins 1 jour@200F]|288143 |
|[Ndeko_19Mins 1 jour@230F]                                                                         |578988 |
|[SMS Bundle 2 Days @66F ]                                                                          |3454376|
|[SMS Bundle 2 Days @66F , Forfait Maxivoice 16Mins 1 jour@200F]                                    |744874 |
|[SMS Bundle 2 Days @66F , Forfait Maxivoice 5Mins 1 jour@100F]                                     |699124 |
|[SMS Bundle 2 Days @66F , SMS Bundle 1 Day @26F ]                                                  |1064410|
|[SMS Bundle 2 Days @66F , SMS Bundle 1 Day @26F , Forfait Maxivoice 16Mins 1 jour@200F]            |247158 |
|[SMS Bundle 2 Days @66F , SMS Bundle 1 Day @26F , Forfait Maxivoice 5Mins 1 jour@100F]             |266617 |
|[Forfait 12Mins (8min autres) 1 Jour@195F]                                                         |519887 |
|[SDP VAS]                                                                                          |2768660|
|[SDP VAS, Forfait Maxivoice 16Mins 1 jour@200F]                                                    |491830 |
|[SDP VAS, Forfait Maxivoice 5Mins 1 jour@100F]                                                     |433880 |
|[SDP VAS, SMS Bundle 1 Day @26F ]                                                                  |279499 |
|[SDP VAS, SMS Bundle 2 Days @66F ]                                                                 |291376 |
|[Ndeko_bon_plan_12Mins 1 Jour@195F]                                                                |504925 |
|[SMS Bundle 1 Day @41F ]                                                                           |2436153|
|[SMS Bundle 1 Day @41F , Forfait Maxivoice 16Mins 1 jour@200F]                                     |529673 |
|[SMS Bundle 1 Day @41F , Forfait Maxivoice 5Mins 1 jour@100F]                                      |542458 |
|[SMS Bundle 1 Day @41F , SMS Bundle 1 Day @26F ]                                                   |927642 |
|[SMS Bundle 1 Day @41F , SMS Bundle 1 Day @26F , Forfait Maxivoice 5Mins 1 jour@100F]              |251032 |
|[SMS Bundle 1 Day @41F , SMS Bundle 2 Days @66F ]                                                  |1027038|
|[SMS Bundle 1 Day @41F , SMS Bundle 2 Days @66F , Forfait Maxivoice 16Mins 1 jour@200F]            |242349 |
|[SMS Bundle 1 Day @41F , SMS Bundle 2 Days @66F , Forfait Maxivoice 5Mins 1 jour@100F]             |253315 |
|[SMS Bundle 1 Day @41F , SMS Bundle 2 Days @66F , SMS Bundle 1 Day @26F ]                          |425529 |
|[Ndeko_53Min 7 jours@590F]                                                                         |502534 |
|[Forfait Maxivoice 10Mins 1 jour@150F]                                                             |2108385|
|[Forfait Maxivoice 10Mins 1 jour@150F, Forfait Maxivoice 16Mins 1 jour@200F]                       |390085 |
|[Forfait Maxivoice 10Mins 1 jour@150F, Forfait Maxivoice 5Mins 1 jour@100F]                        |599152 |
|[Forfait Maxivoice 10Mins 1 jour@150F, SMS Bundle 1 Day @26F ]                                     |375227 |
|[Forfait Maxivoice 10Mins 1 jour@150F, SMS Bundle 2 Days @66F ]                                    |299962 |
|[Forfait Maxivoice 10Mins 1 jour@150F, SDP VAS]                                                    |255500 |
|[Illimite 2H@250F]                                                                                 |477540 |
|[SMS Bundle 3 Days@122F]                                                                           |1952304|
|[SMS Bundle 3 Days@122F, Forfait Maxivoice 16Mins 1 jour@200F]                                     |422292 |
|[SMS Bundle 3 Days@122F, Forfait Maxivoice 5Mins 1 jour@100F]                                      |357947 |
|[SMS Bundle 3 Days@122F, SMS Bundle 1 Day @26F ]                                                   |505365 |
|[SMS Bundle 3 Days@122F, SMS Bundle 2 Days @66F ]                                                  |952852 |
|[SMS Bundle 3 Days@122F, SMS Bundle 2 Days @66F , SMS Bundle 1 Day @26F ]                          |306062 |
|[SMS Bundle 3 Days@122F, SMS Bundle 1 Day @41F ]                                                   |501848 |
|[SMS Bundle 3 Days@122F, SMS Bundle 1 Day @41F , SMS Bundle 2 Days @66F ]                          |322806 |
|[Forfait widge 351MB 3 jours@385F]                                                                 |467295 |
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F]                                                     |1924037|
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, Forfait Maxivoice 16Mins 1 jour@200F]               |277227 |
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, Forfait Maxivoice 5Mins 1 jour@100F]                |284769 |
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 1 Day @26F ]                             |435974 |
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 2 Days @66F ]                            |637645 |
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, SDP VAS]                                            |271969 |
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 1 Day @41F ]                             |400430 |
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 3 Days@122F]                             |330548 |
|[Forfait Classic 120MB 1 jour@190F]                                                                |415374 |
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F]                                                       |1538443|
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, Forfait Maxivoice 16Mins 1 jour@200F]                 |257863 |
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, Forfait Maxivoice 5Mins 1 jour@100F]                  |288339 |
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 1 Day @26F ]                               |336703 |
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 2 Days @66F ]                              |354283 |
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, SDP VAS]                                              |247778 |
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 1 Day @41F ]                               |256168 |
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, 50 SMS vers MTN ou 16 vers autre 2 jours@66F]         |513346 |
|[Forfait widge 1005.47MB 3 jours@660F upsell]                                                      |409037 |
|[Forfait Maxivoice 7Mins 1 jour@120F]                                                              |1526363|
|[Forfait Maxivoice 7Mins 1 jour@120F, Forfait Maxivoice 16Mins 1 jour@200F]                        |477522 |
|[Forfait Maxivoice 7Mins 1 jour@120F, Forfait Maxivoice 5Mins 1 jour@100F]                         |406296 |
|[Forfait Maxivoice 7Mins 1 jour@120F, SMS Bundle 1 Day @26F ]                                      |333356 |
|[Forfait Maxivoice 7Mins 1 jour@120F, SMS Bundle 2 Days @66F ]                                     |281988 |
|[Forfait widge 745.88MB 3 jours@550F upsell]                                                       |356321 |
|[Maxivoice 43Mins jour@525F]                                                                       |1420457|
|[Forfait 1GB 3 Jours@660F]                                                                         |311371 |
|[Forfait weekend 3.17GB 3jours@840F]                                                               |1241892|
|[Maxivoice 180Mins 7 jour@1400F]                                                                   |272298 |
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F]                                                   |1077110|
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, SMS Bundle 2 Days @66F ]                          |349817 |
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, SMS Bundle 3 Days@122F]                           |283214 |
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, 50 SMS vers MTN ou 16 vers autre 2 jours@66F]     |407976 |
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, 15 SMS vers MTN ou 6 vers autre 1 jour@26F]       |263216 |
|[Forfait 385MB 3 Jours@385F]                                                                       |271394 |
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F]                                                      |1039633|
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, SMS Bundle 2 Days @66F ]                             |273444 |
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, 50 SMS vers MTN ou 16 vers autre 2 jours@66F]        |381380 |
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, 15 SMS vers MTN ou 6 vers autre 1 jour@26F]          |338373 |
|[Maximise 1.5GB 1 jour@650F]                                                                       |242872 |
|[MaGicvoice 40+3Mins 7 jours@525F]                                                                 |909599 |
|[Maxivoice 130Mins 7 jour@1050F]                                                                   |242260 |
|[MaGicvoice 51Mins 1 jour@450F]                                                                    |877932 |
|[MaGicvoice 51Mins 1 jour@450F, Forfait Maxivoice 16Mins 1 jour@200F]                              |332752 |
|[NDEKO Net 220MB 1 jour@281F]                                                                      |875231 |
|[NDEKO Net 170MB 1 jour@220F]                                                                      |766554 |
|[Ndeko_11Mins 1 jour@185F]                                                                         |739327 |
|[Ndeko_28Mins 1 jour@300F]                                                                         |703120 |
|[Forfait maximise 1.5GB 1 jours@650F]                                                              |677124 |
|[Maxivoice 19Mins jour@220F]                                                                       |646352 |
+---------------------------------------------------------------------------------------------------+-------+

In [30]:
print("Association Rules Without Free Bundles:")
association_rules = model.associationRules.show(n=100, truncate=False)
association_rules
association_rules_df = pd.DataFrame(model.associationRules.collect(), columns=model.associationRules.columns)
association_rules_df.to_csv("no_free_bundles_association_rules_weekly.csv", index=False)

Association Rules Without Free Bundles:
+-------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------+------------------+------------------+---------------------+
|antecedent                                                                                                                                 |consequent                                    |confidence        |lift              |support              |
+-------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------+------------------+------------------+---------------------+
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, SMS Bundle 3 Days@122F, Forfait Maxivoice 16Mins 1 jour@200F]                             |[SMS Bundle 2 Days @66F ]                     |0.5276287139746602|3.668093308679995 |0.0012814937766040086|
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, 15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 3 Days@122F]                       |[SMS Bundle 2 Days @66F ]                     |0.5297666631472572|3.682956406245754 |0.001462547714562554 |
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, 15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 3 Days@122F]                       |[50 SMS vers MTN ou 16 vers autre 2 jours@66F]|0.572995067798911 |7.151860329334614 |0.0015818900756916225|
|[Illimite 3H@320F, SMS Bundle 2 Days @66F ]                                                                                                |[Illimite 2H@250F]                            |0.6164070612668744|30.99840943401913 |0.001359486882812922 |
|[MaGicvoice 51Mins 1 jour@450F, Forfait Maxivoice 7Mins 1 jour@120F]                                                                       |[Forfait Maxivoice 16Mins 1 jour@200F]        |0.5166959064327485|2.6288312758646617|0.0014716670366446425|
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 1 Day @41F , SMS Bundle 2 Days @66F , SMS Bundle 1 Day @26F ]                      |[50 SMS vers MTN ou 16 vers autre 2 jours@66F]|0.5060272813788728|6.315999286270789 |0.0011956305705160325|
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 3 Days@122F, SMS Bundle 1 Day @41F , SMS Bundle 1 Day @26F ]                     |[SMS Bundle 2 Days @66F ]                     |0.7436659685156408|5.16999187261112  |0.0013750188788705432|
|[Illimite 3H@320F, SMS Bundle 1 Day @26F ]                                                                                                 |[Illimite 2H@250F]                            |0.6396092261848632|32.16521989593248 |0.0014122040597806123|
|[Forfait Maxivoice 7Mins 1 jour@120F, SMS Bundle 3 Days@122F, SMS Bundle 1 Day @41F ]                                                      |[SMS Bundle 2 Days @66F ]                     |0.6465679206536462|4.494962841371592 |0.001232399344025093 |
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, SMS Bundle 3 Days@122F, SMS Bundle 1 Day @26F ]                                           |[SMS Bundle 2 Days @66F ]                     |0.6275913347027763|4.363036950864959 |0.0020737088570228963|
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 1 Day @41F , Forfait Maxivoice 5Mins 1 jour@100F]                                |[SMS Bundle 2 Days @66F ]                     |0.5991739976365829|4.165478627782463 |0.0020902402308429382|
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 3 Days@122F, SMS Bundle 1 Day @41F ]                                             |[SMS Bundle 2 Days @66F ]                     |0.6780518780788177|4.713840416649999 |0.002934589517868104 |
|[NDEKO Net 220MB 1 jour@281F, SMS Bundle 3 Days@122F]                                                                                      |[SMS Bundle 2 Days @66F ]                     |0.5001939801493647|3.4773660777605344|0.0012884894209409534|
|[Illimite 3H@320F]                                                                                                                         |[Illimite 2H@250F]                            |0.5523503433605401|27.77707000844704 |0.004973694919867184 |
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, SDP VAS, SMS Bundle 2 Days @66F ]                                                             |[50 SMS vers MTN ou 16 vers autre 2 jours@66F]|0.5664611761446284|7.070307305330517 |0.001362151890179377 |
|[SMS Bundle 3 Days@122F, SMS Bundle 1 Day @26F , Forfait Maxivoice 5Mins 1 jour@100F, Forfait Maxivoice 16Mins 1 jour@200F]                |[SMS Bundle 2 Days @66F ]                     |0.6393096929005987|4.4445033876901014|0.0010983161609003193|
|[SMS Bundle 3 Days@122F, SMS Bundle 1 Day @41F , Forfait Maxivoice 16Mins 1 jour@200F]                                                     |[SMS Bundle 2 Days @66F ]                     |0.6277303931766174|4.36400369024798  |0.00301562239810438  |
|[SMS Bundle 3 Days@122F, SMS Bundle 1 Day @41F ]                                                                                           |[SMS Bundle 2 Days @66F ]                     |0.6432346049002885|4.471789513448434 |0.013441880748998655 |
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, 100 SMS vers MTN ou 30 vers autre 3 jours@122F, 50 SMS vers MTN ou 16 vers autre 2 jours@66F]|[15 SMS vers MTN ou 6 vers autre 1 jour@26F]  |0.5047753564702717|7.8794933666299345|0.0021875962811987518|
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, SDP VAS, SMS Bundle 2 Days @66F ]                                                         |[50 SMS vers MTN ou 16 vers autre 2 jours@66F]|0.5127524871872173|6.399940205364686 |0.0010623385614531753|
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, SMS Bundle 1 Day @41F , SMS Bundle 1 Day @26F ]                                              |[SMS Bundle 2 Days @66F ]                     |0.5285709193312658|3.674643553335811 |0.001852346682646717 |
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, 50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 1 Day @26F ]                     |[SMS Bundle 2 Days @66F ]                     |0.5626377277005703|3.9114771988859105|0.0021157243637846654|
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 1 Day @26F , Forfait Maxivoice 5Mins 1 jour@100F]                                |[SMS Bundle 2 Days @66F ]                     |0.5619384608558688|3.9066158712778867|0.0021095615342497376|
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, 50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 1 Day @41F ]                         |[SMS Bundle 2 Days @66F ]                     |0.5431284196974574|3.775847806004476 |0.002529674961127328 |
|[SMS Bundle 3 Days@122F, SMS Bundle 1 Day @26F ]                                                                                           |[SMS Bundle 2 Days @66F ]                     |0.6056256369158924|4.210330650130111 |0.012744648196749832 |
|[SMS Bundle 3 Days@122F, SMS Bundle 1 Day @41F , Forfait Maxivoice 5Mins 1 jour@100F, Forfait Maxivoice 16Mins 1 jour@200F]                |[SMS Bundle 2 Days @66F ]                     |0.6638785475994778|4.615306926496782 |0.0011435380046498549|
|[SMS Bundle 3 Days@122F, Forfait Maxivoice 5Mins 1 jour@100F, Forfait Maxivoice 16Mins 1 jour@200F]                                        |[SMS Bundle 2 Days @66F ]                     |0.5667940278834762|3.9403719434022504|0.003008251987106528 |
|[SMS Bundle 3 Days@122F, Forfait Maxivoice 10Mins 1 jour@150F, SMS Bundle 1 Day @26F ]                                                     |[SMS Bundle 2 Days @66F ]                     |0.6123790357112272|4.257280515207403 |0.0011910500891049378|
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, SMS Bundle 3 Days@122F, Forfait Maxivoice 5Mins 1 jour@100F]                              |[SMS Bundle 2 Days @66F ]                     |0.5636042402826855|3.9181964282252415|0.0012220724404800793|
|[SMS Bundle 3 Days@122F, SMS Bundle 1 Day @41F , Forfait Maxivoice 5Mins 1 jour@100F]                                                      |[SMS Bundle 2 Days @66F ]                     |0.6546981466646264|4.551484457498733 |0.0030287392312361517|
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, SMS Bundle 3 Days@122F, SMS Bundle 1 Day @26F ]                                              |[SMS Bundle 2 Days @66F ]                     |0.6486790068565278|4.509639186630559 |0.0011542813155958772|
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, 50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 1 Day @41F ]                     |[SMS Bundle 2 Days @66F ]                     |0.5734475763036505|3.9866276451724763|0.0021068965268832827|
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, SMS Bundle 3 Days@122F]                                                                      |[SMS Bundle 2 Days @66F ]                     |0.5319526012932313|3.6981531248360557|0.0029871817726154918|
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, 50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 1 Day @41F ]                        |[SMS Bundle 2 Days @66F ]                     |0.5369761709120788|3.733077156861856 |0.0019048556559139033|
|[MaGicvoice 51Mins 1 jour@450F, SMS Bundle 2 Days @66F , SMS Bundle 1 Day @26F ]                                                           |[Forfait Maxivoice 16Mins 1 jour@200F]        |0.507397327549162 |2.5815222209913022|0.0010325237915409585|
|[SMS Bundle 3 Days@122F, SDP VAS, SMS Bundle 1 Day @26F ]                                                                                  |[SMS Bundle 2 Days @66F ]                     |0.7020067483573078|4.880375514250936 |0.0014814526105683449|
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, 15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 2 Days @66F ]                         |[50 SMS vers MTN ou 16 vers autre 2 jours@66F]|0.606445365625442 |7.569371528774733 |0.0023210132124819116|
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, 15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 3 Days@122F]                          |[SMS Bundle 2 Days @66F ]                     |0.5483592400690847|3.8122126525260667|0.0010047910586337848|
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, 15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 3 Days@122F]                          |[50 SMS vers MTN ou 16 vers autre 2 jours@66F]|0.6130351786201255|7.65162253717425  |0.0011233006049608362|
|[MaGicvoice 51Mins 1 jour@450F, Forfait Maxivoice 5Mins 1 jour@100F]                                                                       |[Forfait Maxivoice 16Mins 1 jour@200F]        |0.5255122794528906|2.673686976957884 |0.0034429396730194196|
|[SMS Bundle 3 Days@122F, SMS Bundle 1 Day @41F , SMS Bundle 1 Day @26F ]                                                                   |[SMS Bundle 2 Days @66F ]                     |0.7103433038391532|4.938331540089714 |0.005622832417299512 |
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 1 Day @41F ]                                                                     |[SMS Bundle 2 Days @66F ]                     |0.5358839247808606|3.7254838234832146|0.008935436573803236 |
|[MTN Call Me Back, SMS Bundle 1 Day @41F , SMS Bundle 2 Days @66F ]                                                                        |[SMS Bundle 1 Day @26F ]                      |0.5266658274588788|3.212069944738639 |0.0010453074987519229|
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, 50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 3 Days@122F]                         |[SMS Bundle 2 Days @66F ]                     |0.5648070959351762|3.9265587228717393|0.0021159325674851696|
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, 50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 3 Days@122F]                        |[SMS Bundle 2 Days @66F ]                     |0.5640265630061548|3.9211324305978033|0.0014500554925322953|
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 3 Days@122F, SDP VAS]                                                            |[SMS Bundle 2 Days @66F ]                     |0.5502608301202087|3.825432573196865 |0.0010102459955869977|
|[MTN Call Me Back, SMS Bundle 1 Day @41F ]                                                                                                 |[SMS Bundle 2 Days @66F ]                     |0.5027848101265823|3.495377618549832 |0.0019847642361674562|
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, 100 SMS vers MTN ou 30 vers autre 3 jours@122F, SMS Bundle 3 Days@122F]                      |[50 SMS vers MTN ou 16 vers autre 2 jours@66F]|0.5859757077583634|7.3138786942256075|0.001062713328114083 |
|[SMS Bundle 3 Days@122F, Forfait Maxivoice 10Mins 1 jour@150F, SMS Bundle 1 Day @41F ]                                                     |[SMS Bundle 2 Days @66F ]                     |0.6351020933424846|4.415252008119685 |0.001233023955126606 |
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, SMS Bundle 3 Days@122F, SMS Bundle 1 Day @41F ]                                           |[SMS Bundle 2 Days @66F ]                     |0.6331158588140278|4.401443636076364 |0.0020891159308602148|
|[MTN Call Me Back, SMS Bundle 3 Days@122F]                                                                                                 |[SMS Bundle 2 Days @66F ]                     |0.5925870671506954|4.11968605622582  |0.001488614817865693 |
|[SMS Bundle 1 Day @41F , SDP VAS, SMS Bundle 1 Day @26F ]                                                                                  |[SMS Bundle 2 Days @66F ]                     |0.5387951678995264|3.7457228876597557|0.0016863666926046836|
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, 100 SMS vers MTN ou 30 vers autre 3 jours@122F]                                              |[50 SMS vers MTN ou 16 vers autre 2 jours@66F]|0.5781229169444074|7.215863778822174 |0.004333801666737248 |
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, 50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 1 Day @26F ]                         |[SMS Bundle 2 Days @66F ]                     |0.5190489547412015|3.608446521837673 |0.002619868804185794 |
|[MTN Call Me Back, SMS Bundle 1 Day @41F , SMS Bundle 1 Day @26F ]                                                                         |[SMS Bundle 2 Days @66F ]                     |0.561701461144302 |3.9049682409781465|0.0010453074987519229|
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, SMS Bundle 1 Day @26F , Forfait Maxivoice 5Mins 1 jour@100F]                              |[SMS Bundle 2 Days @66F ]                     |0.5915322091471552|4.112352646420948 |0.0010152012436590002|
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 1 Day @41F , SMS Bundle 2 Days @66F ]                                              |[50 SMS vers MTN ou 16 vers autre 2 jours@66F]|0.5039402737453339|6.289950218939963 |0.002529674961127328 |
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 1 Day @41F , SMS Bundle 1 Day @26F ]                                             |[SMS Bundle 2 Days @66F ]                     |0.6089652728561304|4.233547916213933 |0.004007338264346494 |
|[SMS Bundle 3 Days@122F, SDP VAS]                                                                                                          |[SMS Bundle 2 Days @66F ]                     |0.5855309742154984|4.070631850881219 |0.004235362957138811 |
|[Illimite 3H@320F, Forfait Maxivoice 16Mins 1 jour@200F]                                                                                   |[Illimite 2H@250F]                            |0.6268317853457173|31.52265694112668 |0.0013910922045494757|
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, 100 SMS vers MTN ou 30 vers autre 3 jours@122F, 15 SMS vers MTN ou 6 vers autre 1 jour@26F]  |[50 SMS vers MTN ou 16 vers autre 2 jours@66F]|0.6865076772296635|8.568672399612257 |0.0021875962811987518|
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, 15 SMS vers MTN ou 6 vers autre 1 jour@26F, SDP VAS]                                      |[50 SMS vers MTN ou 16 vers autre 2 jours@66F]|0.6261426803819091|7.815224332608347 |0.0014118292931197046|
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 3 Days@122F, SMS Bundle 1 Day @26F ]                                               |[SMS Bundle 2 Days @66F ]                     |0.652033188203401 |4.532957572891007 |0.0016525544116427842|
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 3 Days@122F, SMS Bundle 1 Day @26F ]                                               |[50 SMS vers MTN ou 16 vers autre 2 jours@66F]|0.5017169144828719|6.262199273424598 |0.0012715832804600035|
|[SMS Bundle 3 Days@122F, SMS Bundle 1 Day @26F , Forfait Maxivoice 5Mins 1 jour@100F]                                                      |[SMS Bundle 2 Days @66F ]                     |0.628233450980047 |4.367500965725538 |0.0029722327469192825|
|[Illimite 2H@250F, SMS Bundle 3 Days@122F]                                                                                                 |[SMS Bundle 2 Days @66F ]                     |0.5349318815285629|3.7188651854318087|0.0017102268366824772|
|[SMS Bundle 3 Days@122F, SMS Bundle 1 Day @41F , SDP VAS]                                                                                  |[SMS Bundle 2 Days @66F ]                     |0.7501999516396034|5.215416352252283 |0.0016794959704880415|
|[Forfait Maxivoice 7Mins 1 jour@120F, SMS Bundle 3 Days@122F, SMS Bundle 1 Day @26F ]                                                      |[SMS Bundle 2 Days @66F ]                     |0.6230682897349564|4.331592583752453 |0.001202084885231666 |
|[25 SMS vers MTN ou 10 vers autre 1 jour@41F, 15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 1 Day @41F ]                          |[50 SMS vers MTN ou 16 vers autre 2 jours@66F]|0.5422193603777634|6.767732134552738 |0.0015778925646419398|
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 3 Days@122F]                                                                     |[SMS Bundle 2 Days @66F ]                     |0.5548089838692112|3.857051497436013 |0.007636536967837067 |
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, 15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 2 Days @66F ]                      |[50 SMS vers MTN ou 16 vers autre 2 jours@66F]|0.6157589700482237|7.685619646320107 |0.0023182232828951542|
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 3 Days@122F, SMS Bundle 1 Day @41F ]                                               |[SMS Bundle 2 Days @66F ]                     |0.6669285689884877|4.636510782071813 |0.001625904337978233 |
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 3 Days@122F, SMS Bundle 1 Day @41F ]                                               |[50 SMS vers MTN ou 16 vers autre 2 jours@66F]|0.507891230827042 |6.339264244144607 |0.0012381874068991127|
|[15 SMS vers MTN ou 6 vers autre 1 jour@26F, SMS Bundle 3 Days@122F]                                                                       |[SMS Bundle 2 Days @66F ]                     |0.537417928987401 |3.7361482744815513|0.004161658847160287 |
|[Forfait Maxivoice 7Mins 1 jour@120F, SMS Bundle 3 Days@122F, Forfait Maxivoice 16Mins 1 jour@200F]                                        |[SMS Bundle 2 Days @66F ]                     |0.5604255911956256|3.896098348386004 |0.0013401239386660214|
|[50 SMS vers MTN ou 16 vers autre 2 jours@66F, SMS Bundle 1 Day @26F ]                                                                     |[SMS Bundle 2 Days @66F ]                     |0.5004449806639846|3.4791110421337144|0.009085218315946034 |
|[100 SMS vers MTN ou 30 vers autre 3 jours@122F, SMS Bundle 1 Day @26F ]                                                                   |[SMS Bundle 2 Days @66F ]                     |0.5173284138260184|3.5964852611042466|0.004694160631570102 |

In [ ]:
no_free_buundles_association_rules_df = pd.read_csv("no_free_bundles_association_rules_weekly.csv")
no_free_bundles_freq_rules_df = pd.read_csv("no_free_bundles_freq_rules_weekly.csv")
# clean duplicated " '' " in the consequent and antecedent
def clean_string_list(lst):
    return [item.replace("'", "") for item in lst]

no_free_buundles_association_rules_df['antecedent'] = no_free_buundles_association_rules_df['antecedent'].apply(lambda x: clean_string_list(ast.literal_eval(x)))
no_free_buundles_association_rules_df['consequent'] = no_free_buundles_association_rules_df['consequent'].apply(lambda x: clean_string_list(ast.literal_eval(x)))

# remove also duplicated " '' " from fre_rules
no_free_bundles_freq_rules_df['items'] = no_free_bundles_freq_rules_df['items'].apply(lambda x: clean_string_list(ast.literal_eval(x)))

In [ ]:
display(no_free_buundles_association_rules_df.head(20))
print(no_free_buundles_association_rules_df.shape)

In [ ]:
display(no_free_bundles_freq_rules_df.head(10))
print(no_free_bundles_freq_rules_df.shape)